"""The `arcc_check_test` rule: run `arcc check` on a generated component,
hermetically, as a Bazel test.

This ties the pieces together: Step 4's generated manifest and layout, Step 1's
package-layout loading mode, and Step 5a's SDK stdlib resolution. The test's
action writes a launcher that `cd`s to the runfiles root — the frame every path
in the manifest and layout is expressed in (design §5.4) — and execs arcc
there. No `local`/`external` tags: with the layout's sources and the rules_go
SDK stdlib declared as runfiles, the check is sandboxed and cacheable, and
needs no `go.mod` or `go` binary (design §4.5).
"""

load("//bazel_rules:providers.bzl", "ArccComponentInfo")
load("//bazel_rules/go:providers.bzl", "ArccStdlibMapInfo")
load(":command.bzl", "arcc_check_argv")
load(":go_adapter.bzl", "ARCC_TARGET", "GO_TOOLCHAINS", "go_sdk_srcs")
load(":paths.bzl", "runfiles_path")
load(":stdlib_map.bzl", "stdlib_map_default_attr")

def _shell_quote(arg):
    # Runfiles-root-relative paths hold no shell metacharacters, but quoting is
    # free insurance and keeps the generated script obviously safe to read.
    return "'" + arg.replace("'", "'\\''") + "'"

def _launcher_content(argv, expect_violation):
    command = " ".join([_shell_quote(arg) for arg in argv])

    if expect_violation:
        # The negative path: the check is expected to report a violation
        # (arcc's exit 1). Conforming (0) or a tool error (2) is a test failure.
        verdict = "\n".join([
            'if [ "$status" -eq 1 ]; then',
            "  exit 0",
            "fi",
            'echo "arcc_check_test: expected a violation (exit 1), got exit $status" >&2',
            "exit 1",
        ])
    else:
        # The normal path: arcc's own exit-code mapping is the test result —
        # 0 conforms (pass), 1 violation and 2 tool error both fail the test,
        # distinguishable in the log.
        verdict = 'exit "$status"'

    return "\n".join([
        "#!/bin/sh",
        "# Generated by arcc_check_test — do not edit.",
        "#",
        "# Bazel starts a test with the runfiles root at $TEST_SRCDIR. Every path",
        "# in the manifest and layout — sources, the Go SDK stdlib, the manifest",
        "# and layout themselves — is named relative to that root, so the check",
        "# runs from there.",
        "set -u",
        'cd "${TEST_SRCDIR:?TEST_SRCDIR is not set}" || exit 2',
        "",
        command,
        "status=$?",
        "",
        verdict,
        "",
    ])

def _component_arcc_group(ctx):
    """The component's `arcc` output group (report + surface), or an empty depset.

    Staging the checked analysis artifacts into the test's runfiles builds the
    component's analysis action — and transitively its direct dependencies'
    producer chain — whenever the `.check` runs, even though the assertion
    itself reads only the report verdict (design AC 4; Step 6 turns these
    rules into pure report assertions).
    """
    output_groups = ctx.attr.component[OutputGroupInfo]
    return getattr(output_groups, "arcc", depset())

def _checked_launcher_arg(arg):
    """Quote one launcher argv element.

    Artifact destination arguments name `$TEST_TMPDIR`, which only the shell
    may expand, so they are double-quoted; every other element is a
    runfiles-frame path with no metacharacters and gets the ordinary single
    quoting.
    """
    if "$TEST_TMPDIR" in arg:
        return '"' + arg + '"'
    return _shell_quote(arg)

def _checked_analysis_launcher(argv, expected_report, expected_surface, expect_verdict, map_path, arcc):
    """Launcher for `arcc_checked_analysis_test`.

    Runs the component's exact analysis command twice into the test scratch
    directory, compares both runs' artifacts byte-for-byte with each other and
    with the analysis action's own outputs, and asserts the report verdict.
    `argv` is the factored command with runfiles-frame paths; the two artifact
    destinations are `$TEST_TMPDIR`-relative and double-quoted so the shell
    expands them.
    """
    command = " ".join([_checked_launcher_arg(arg) for arg in argv])
    run1 = command.replace("runX", "run1")
    run2 = run1.replace("run1.report.json", "run2.report.json").replace("run1.surface.json", "run2.surface.json")
    return "\n".join([
        "#!/bin/sh",
        "# Generated by arcc_checked_analysis_test — do not edit.",
        "#",
        "# Execution coverage for the checked-component analysis action: the",
        "# same command the action runs (command.bzl), executed twice in the",
        "# test sandbox, must reproduce the action's report and surface",
        "# byte-identically (determinism), and the report must carry the",
        "# expected verdict — pass for a conforming component, fail for a",
        "# violating one (violations are data, never action failures).",
        "set -eu",
        'cd "${TEST_SRCDIR:?TEST_SRCDIR is not set}" || exit 2',
        "",
        run1,
        run2,
        "",
        'if ! cmp -s "$TEST_TMPDIR/run1.report.json" "$TEST_TMPDIR/run2.report.json"; then',
        '  echo "arcc_checked_analysis_test: report differs between identical runs" >&2',
        "  exit 1",
        "fi",
        'if ! cmp -s "$TEST_TMPDIR/run1.surface.json" "$TEST_TMPDIR/run2.surface.json"; then',
        '  echo "arcc_checked_analysis_test: surface differs between identical runs" >&2',
        "  exit 1",
        "fi",
        'if ! cmp -s ' + _shell_quote(expected_report) + ' "$TEST_TMPDIR/run1.report.json"; then',
        '  echo "arcc_checked_analysis_test: reproduced report differs from the analysis action\'s report" >&2',
        "  diff -u " + _shell_quote(expected_report) + ' "$TEST_TMPDIR/run1.report.json" >&2 || true',
        "  exit 1",
        "fi",
        'if ! cmp -s ' + _shell_quote(expected_surface) + ' "$TEST_TMPDIR/run1.surface.json"; then',
        '  echo "arcc_checked_analysis_test: reproduced surface differs from the analysis action\'s surface" >&2',
        "  diff -u " + _shell_quote(expected_surface) + ' "$TEST_TMPDIR/run1.surface.json" >&2 || true',
        "  exit 1",
        "fi",
        "",
        'if ! grep -q \'"verdict": "' + expect_verdict + '"\' "$TEST_TMPDIR/run1.report.json"; then',
        '  echo "arcc_checked_analysis_test: expected verdict ' + expect_verdict + ' in report:" >&2',
        '  cat "$TEST_TMPDIR/run1.report.json" >&2',
        "  exit 1",
        "fi",
        "",
        "# Target identity (AC 6): the surface's SDK key must identify the",
        "# attached stdlib map exactly. The action itself already validated",
        "# the full key (including classifier hash and tags) against the",
        "# layout's pinned platform; this re-checks the identity fields the",
        "# surface carries against the map artifact.",
        'toolchain=$(sed -n \'s/.*"toolchainVersion": "\\([^"]*\\)".*/\\1/p\' "$TEST_TMPDIR/run1.surface.json")',
        'goos=$(sed -n \'s/.*"goos": "\\([^"]*\\)".*/\\1/p\' "$TEST_TMPDIR/run1.surface.json")',
        'goarch=$(sed -n \'s/.*"goarch": "\\([^"]*\\)".*/\\1/p\' "$TEST_TMPDIR/run1.surface.json")',
        'if [ -z "$toolchain" ] || [ -z "$goos" ] || [ -z "$goarch" ]; then',
        '  echo "arcc_checked_analysis_test: surface carries no SDK key identity fields" >&2',
        '  cat "$TEST_TMPDIR/run1.surface.json" >&2',
        "  exit 1",
        "fi",
        'if ! ' + _shell_quote(arcc) + ' stdlibmap inspect ' + _shell_quote(map_path) +
        ' --expect-key="toolchain_version=$toolchain,goos=$goos,goarch=$goarch" >/dev/null 2>&1; then',
        '  echo "arcc_checked_analysis_test: surface SDK key does not identify the attached stdlib map" >&2',
        "  exit 1",
        "fi",
        "",
        "exit 0",
        "",
    ])

def _arcc_checked_analysis_impl(ctx):
    info = ctx.attr.component[ArccComponentInfo]

    map_file = ctx.attr._stdlib_map[ArccStdlibMapInfo].map
    argv = arcc_check_argv(
        arcc = runfiles_path(ctx, ctx.executable._arcc),
        manifest = runfiles_path(ctx, info.manifest),
        layout = runfiles_path(ctx, info.layout),
        stdlib_map = runfiles_path(ctx, map_file),
        report_out = "$TEST_TMPDIR/runX.report.json",
        surface_out = "$TEST_TMPDIR/runX.surface.json",
        verdict_only = True,
    )

    launcher = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(
        output = launcher,
        content = _checked_analysis_launcher(
            argv,
            runfiles_path(ctx, info.report),
            runfiles_path(ctx, info.surface),
            ctx.attr.expect_verdict,
            runfiles_path(ctx, map_file),
            runfiles_path(ctx, ctx.executable._arcc),
        ),
        is_executable = True,
    )

    # The stdlib source the layout names lives in the Go SDK; arcc type-checks
    # the closure from it, so it must be present in the sandbox. The arcc
    # output group brings the action's own report and surface — and, through
    # the action's declared inputs, the dependency producer chain — into the
    # test's build graph.
    runfiles = ctx.runfiles(transitive_files = go_sdk_srcs(ctx))
    runfiles = runfiles.merge(ctx.attr.component[DefaultInfo].default_runfiles)
    runfiles = runfiles.merge(ctx.attr._arcc[DefaultInfo].default_runfiles)
    runfiles = runfiles.merge(ctx.runfiles(files = [map_file]))
    runfiles = runfiles.merge(ctx.runfiles(transitive_files = _component_arcc_group(ctx)))

    return [DefaultInfo(executable = launcher, runfiles = runfiles)]

arcc_checked_analysis_test = rule(
    implementation = _arcc_checked_analysis_impl,
    test = True,
    attrs = {
        "component": attr.label(
            mandatory = True,
            providers = [ArccComponentInfo],
            doc = "The checked go_component target whose analysis to re-execute.",
        ),
        "expect_verdict": attr.string(
            default = "pass",
            doc = "The report verdict the analysis must produce: \"pass\" for a " +
                  "conforming component, \"fail\" for a violating one.",
        ),
        "_arcc": attr.label(
            default = ARCC_TARGET,
            executable = True,
            cfg = "target",
            doc = "The arcc binary the check runs.",
        ),
        "_stdlib_map": stdlib_map_default_attr(),
    },
    toolchains = GO_TOOLCHAINS,
    doc = "Re-executes a checked component's analysis command and requires " +
          "byte-identical report/surface artifacts and the expected verdict.",
)

def _arcc_check_impl(ctx):
    info = ctx.attr.component[ArccComponentInfo]

    layout_path = runfiles_path(ctx, info.layout) if info.layout != None else ""
    argv = arcc_check_argv(
        arcc = runfiles_path(ctx, ctx.executable._arcc),
        manifest = runfiles_path(ctx, info.manifest),
        layout = layout_path,
    )

    launcher = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(
        output = launcher,
        content = _launcher_content(argv, ctx.attr.expect_violation),
        is_executable = True,
    )

    # The stdlib source the layout names lives in the Go SDK; arcc type-checks
    # the closure from it, so it must be present in the sandbox.
    runfiles = ctx.runfiles(transitive_files = go_sdk_srcs(ctx))
    runfiles = runfiles.merge(ctx.attr.component[DefaultInfo].default_runfiles)
    runfiles = runfiles.merge(ctx.attr._arcc[DefaultInfo].default_runfiles)
    runfiles = runfiles.merge(ctx.runfiles(transitive_files = _component_arcc_group(ctx)))

    return [DefaultInfo(executable = launcher, runfiles = runfiles)]

arcc_check_test = rule(
    implementation = _arcc_check_impl,
    test = True,
    attrs = {
        "component": attr.label(
            mandatory = True,
            providers = [ArccComponentInfo],
            doc = "The go_component target to check.",
        ),
        "expect_violation": attr.bool(
            default = False,
            doc = "Test-only. When true the test passes iff arcc reports a " +
                  "violation (exit 1) rather than conforming — used to " +
                  "exercise the negative path. Real `.check` targets, which " +
                  "the go_component macro generates, leave this False.",
        ),
        "_arcc": attr.label(
            default = ARCC_TARGET,
            executable = True,
            cfg = "target",
            doc = "The arcc binary the check runs.",
        ),
    },
    toolchains = GO_TOOLCHAINS,
    doc = "Runs `arcc check` on a go_component's generated manifest and layout, hermetically.",
)

def _launcher_content_with_grep(argv, expected_strings, expect_status = 1):
    command = " ".join([_shell_quote(arg) for arg in argv])
    
    grep_commands = []
    for s in expected_strings:
        grep_commands.append('if ! grep -F %s "$output_file" > /dev/null; then' % _shell_quote(s))
        grep_commands.append('  echo "arcc_check_test: expected string \'%s\' not found in output" >&2' % s)
        grep_commands.append('  cat "$output_file" >&2')
        grep_commands.append('  rm -f "$output_file"')
        grep_commands.append('  exit 1')
        grep_commands.append('fi')

    return "\n".join([
        "#!/bin/sh",
        "set -u",
        'cd "${TEST_SRCDIR:?TEST_SRCDIR is not set}" || exit 2',
        "",
        'output_file=$(mktemp)',
        "status=0",
        command + ' > "$output_file" 2>&1 || status=$?',
        "",
        'if [ "$status" -ne %d ]; then' % expect_status,
        '  echo "arcc_check_test: expected exit %d, got exit $status" >&2' % expect_status,
        '  cat "$output_file" >&2',
        '  rm -f "$output_file"',
        '  exit 1',
        'fi',
        "",
    ] + grep_commands + [
        "",
        'rm -f "$output_file"',
        "exit 0",
        ""
    ])

def _arcc_check_grep_impl(ctx):
    info = ctx.attr.component[ArccComponentInfo]

    layout_path = runfiles_path(ctx, info.layout) if info.layout != None else ""
    argv = arcc_check_argv(
        arcc = runfiles_path(ctx, ctx.executable._arcc),
        manifest = runfiles_path(ctx, info.manifest),
        layout = layout_path,
    )

    launcher = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(
        output = launcher,
        content = _launcher_content_with_grep(argv, ctx.attr.expected_strings, ctx.attr.expect_status),
        is_executable = True,
    )

    runfiles = ctx.runfiles(transitive_files = go_sdk_srcs(ctx))
    runfiles = runfiles.merge(ctx.attr.component[DefaultInfo].default_runfiles)
    runfiles = runfiles.merge(ctx.attr._arcc[DefaultInfo].default_runfiles)

    return [DefaultInfo(executable = launcher, runfiles = runfiles)]

arcc_check_grep_test = rule(
    implementation = _arcc_check_grep_impl,
    test = True,
    attrs = {
        "component": attr.label(
            mandatory = True,
            providers = [ArccComponentInfo],
            doc = "The go_component target to check.",
        ),
        "expected_strings": attr.string_list(
            mandatory = True,
            doc = "List of strings to grep in the output of the check.",
        ),
        "expect_status": attr.int(
            default = 1,
            doc = "Expected exit status of the arcc check command.",
        ),
        "_arcc": attr.label(
            default = ARCC_TARGET,
            executable = True,
            cfg = "target",
            doc = "The arcc binary the check runs.",
        ),
    },
    toolchains = GO_TOOLCHAINS,
    doc = "Runs `arcc check` on a go_component, expects exit code, and greps stdout/stderr for specific strings.",
)

def _launcher_content_with_golden(argv, golden_file_path):
    command = " ".join([_shell_quote(arg) for arg in argv])
    return "\n".join([
        "#!/bin/sh",
        "set -u",
        'cd "${TEST_SRCDIR:?TEST_SRCDIR is not set}" || exit 2',
        "",
        'output_file=$(mktemp)',
        "status=0",
        command + ' > "$output_file" 2>&1 || status=$?',
        "",
        'if [ "$status" -ne 0 ]; then',
        '  echo "arcc_check_report_golden_test: check failed with exit $status" >&2',
        '  cat "$output_file" >&2',
        '  rm -f "$output_file"',
        '  exit 1',
        'fi',
        "",
        'if ! diff -u %s "$output_file"; then' % _shell_quote(golden_file_path),
        '  echo "arcc_check_report_golden_test: output differs from golden %s" >&2' % _shell_quote(golden_file_path),
        '  rm -f "$output_file"',
        '  exit 1',
        'fi',
        "",
        'rm -f "$output_file"',
        "exit 0",
        "",
    ])

def _arcc_check_report_golden_impl(ctx):
    info = ctx.attr.component[ArccComponentInfo]

    argv = [
        runfiles_path(ctx, ctx.executable._arcc),
        "check",
        runfiles_path(ctx, info.manifest),
    ]
    if info.layout != None:
        argv.append("--package-layout=" + runfiles_path(ctx, info.layout))
    if ctx.attr.format_json:
        argv.append("--format=json")

    golden_path = runfiles_path(ctx, ctx.file.golden)

    launcher = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(
        output = launcher,
        content = _launcher_content_with_golden(argv, golden_path),
        is_executable = True,
    )

    runfiles = ctx.runfiles(files = [ctx.file.golden], transitive_files = go_sdk_srcs(ctx))
    runfiles = runfiles.merge(ctx.attr.component[DefaultInfo].default_runfiles)
    runfiles = runfiles.merge(ctx.attr._arcc[DefaultInfo].default_runfiles)

    return [DefaultInfo(executable = launcher, runfiles = runfiles)]

arcc_check_report_golden_test = rule(
    implementation = _arcc_check_report_golden_impl,
    test = True,
    attrs = {
        "component": attr.label(
            mandatory = True,
            providers = [ArccComponentInfo],
            doc = "The go_component target to check.",
        ),
        "golden": attr.label(
            mandatory = True,
            allow_single_file = True,
            doc = "Golden report file to compare against.",
        ),
        "format_json": attr.bool(
            default = False,
            doc = "Whether to pass --format=json to arcc check.",
        ),
        "_arcc": attr.label(
            default = ARCC_TARGET,
            executable = True,
            cfg = "target",
            doc = "The arcc binary the check runs.",
        ),
    },
    toolchains = GO_TOOLCHAINS,
    doc = "Runs `arcc check` on a go_component hermetically and compares its report output against a golden file.",
)
