"""The `arcc_check_test` rule: run `arcc check` on a generated component,
hermetically, as a Bazel test.

This ties the pieces together: Step 4's generated manifest and layout, Step 1's
package-layout loading mode, and Step 5a's SDK stdlib resolution. The test's
action writes a launcher that `cd`s to the runfiles root — the frame every path
in the manifest and layout is expressed in (design §5.4) — and execs arcc
there. No `local`/`external` tags: with the layout's sources and the rules_go
SDK stdlib declared as runfiles, the check is sandboxed and cacheable, and
needs no `go.mod` or `go` binary (design §4.5).
"""

load("//bazel_rules:providers.bzl", "ArccComponentInfo")
load(":command.bzl", "arcc_check_argv")
load(":go_adapter.bzl", "ARCC_TARGET", "GO_TOOLCHAINS", "go_sdk_srcs")
load(":paths.bzl", "runfiles_path")

def _shell_quote(arg):
    # Runfiles-root-relative paths hold no shell metacharacters, but quoting is
    # free insurance and keeps the generated script obviously safe to read.
    return "'" + arg.replace("'", "'\\''") + "'"

def _launcher_content(argv, expect_violation):
    command = " ".join([_shell_quote(arg) for arg in argv])

    if expect_violation:
        # The negative path: the check is expected to report a violation
        # (arcc's exit 1). Conforming (0) or a tool error (2) is a test failure.
        verdict = "\n".join([
            'if [ "$status" -eq 1 ]; then',
            "  exit 0",
            "fi",
            'echo "arcc_check_test: expected a violation (exit 1), got exit $status" >&2',
            "exit 1",
        ])
    else:
        # The normal path: arcc's own exit-code mapping is the test result —
        # 0 conforms (pass), 1 violation and 2 tool error both fail the test,
        # distinguishable in the log.
        verdict = 'exit "$status"'

    return "\n".join([
        "#!/bin/sh",
        "# Generated by arcc_check_test — do not edit.",
        "#",
        "# Bazel starts a test with the runfiles root at $TEST_SRCDIR. Every path",
        "# in the manifest and layout — sources, the Go SDK stdlib, the manifest",
        "# and layout themselves — is named relative to that root, so the check",
        "# runs from there.",
        "set -u",
        'cd "${TEST_SRCDIR:?TEST_SRCDIR is not set}" || exit 2',
        "",
        command,
        "status=$?",
        "",
        verdict,
        "",
    ])

def _component_arcc_group(ctx):
    """The component's `arcc` output group (report + surface), or an empty depset.

    Staging the checked analysis artifacts into the test's runfiles builds the
    component's analysis action — and transitively its direct dependencies'
    producer chain — whenever the `.check` runs, even though the assertion
    itself reads only the report verdict (design AC 4; Step 6 turns these
    rules into pure report assertions).
    """
    output_groups = ctx.attr.component[OutputGroupInfo]
    return getattr(output_groups, "arcc", depset())

def _arcc_check_impl(ctx):
    info = ctx.attr.component[ArccComponentInfo]

    layout_path = runfiles_path(ctx, info.layout) if info.layout != None else ""
    argv = arcc_check_argv(
        arcc = runfiles_path(ctx, ctx.executable._arcc),
        manifest = runfiles_path(ctx, info.manifest),
        layout = layout_path,
    )

    launcher = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(
        output = launcher,
        content = _launcher_content(argv, ctx.attr.expect_violation),
        is_executable = True,
    )

    # The stdlib source the layout names lives in the Go SDK; arcc type-checks
    # the closure from it, so it must be present in the sandbox.
    runfiles = ctx.runfiles(transitive_files = go_sdk_srcs(ctx))
    runfiles = runfiles.merge(ctx.attr.component[DefaultInfo].default_runfiles)
    runfiles = runfiles.merge(ctx.attr._arcc[DefaultInfo].default_runfiles)
    runfiles = runfiles.merge(ctx.runfiles(transitive_files = _component_arcc_group(ctx)))

    return [DefaultInfo(executable = launcher, runfiles = runfiles)]

arcc_check_test = rule(
    implementation = _arcc_check_impl,
    test = True,
    attrs = {
        "component": attr.label(
            mandatory = True,
            providers = [ArccComponentInfo],
            doc = "The go_component target to check.",
        ),
        "expect_violation": attr.bool(
            default = False,
            doc = "Test-only. When true the test passes iff arcc reports a " +
                  "violation (exit 1) rather than conforming — used to " +
                  "exercise the negative path. Real `.check` targets, which " +
                  "the go_component macro generates, leave this False.",
        ),
        "_arcc": attr.label(
            default = ARCC_TARGET,
            executable = True,
            cfg = "target",
            doc = "The arcc binary the check runs.",
        ),
    },
    toolchains = GO_TOOLCHAINS,
    doc = "Runs `arcc check` on a go_component's generated manifest and layout, hermetically.",
)

def _launcher_content_with_grep(argv, expected_strings, expect_status = 1):
    command = " ".join([_shell_quote(arg) for arg in argv])
    
    grep_commands = []
    for s in expected_strings:
        grep_commands.append('if ! grep -F %s "$output_file" > /dev/null; then' % _shell_quote(s))
        grep_commands.append('  echo "arcc_check_test: expected string \'%s\' not found in output" >&2' % s)
        grep_commands.append('  cat "$output_file" >&2')
        grep_commands.append('  rm -f "$output_file"')
        grep_commands.append('  exit 1')
        grep_commands.append('fi')

    return "\n".join([
        "#!/bin/sh",
        "set -u",
        'cd "${TEST_SRCDIR:?TEST_SRCDIR is not set}" || exit 2',
        "",
        'output_file=$(mktemp)',
        "status=0",
        command + ' > "$output_file" 2>&1 || status=$?',
        "",
        'if [ "$status" -ne %d ]; then' % expect_status,
        '  echo "arcc_check_test: expected exit %d, got exit $status" >&2' % expect_status,
        '  cat "$output_file" >&2',
        '  rm -f "$output_file"',
        '  exit 1',
        'fi',
        "",
    ] + grep_commands + [
        "",
        'rm -f "$output_file"',
        "exit 0",
        ""
    ])

def _arcc_check_grep_impl(ctx):
    info = ctx.attr.component[ArccComponentInfo]

    layout_path = runfiles_path(ctx, info.layout) if info.layout != None else ""
    argv = arcc_check_argv(
        arcc = runfiles_path(ctx, ctx.executable._arcc),
        manifest = runfiles_path(ctx, info.manifest),
        layout = layout_path,
    )

    launcher = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(
        output = launcher,
        content = _launcher_content_with_grep(argv, ctx.attr.expected_strings, ctx.attr.expect_status),
        is_executable = True,
    )

    runfiles = ctx.runfiles(transitive_files = go_sdk_srcs(ctx))
    runfiles = runfiles.merge(ctx.attr.component[DefaultInfo].default_runfiles)
    runfiles = runfiles.merge(ctx.attr._arcc[DefaultInfo].default_runfiles)

    return [DefaultInfo(executable = launcher, runfiles = runfiles)]

arcc_check_grep_test = rule(
    implementation = _arcc_check_grep_impl,
    test = True,
    attrs = {
        "component": attr.label(
            mandatory = True,
            providers = [ArccComponentInfo],
            doc = "The go_component target to check.",
        ),
        "expected_strings": attr.string_list(
            mandatory = True,
            doc = "List of strings to grep in the output of the check.",
        ),
        "expect_status": attr.int(
            default = 1,
            doc = "Expected exit status of the arcc check command.",
        ),
        "_arcc": attr.label(
            default = ARCC_TARGET,
            executable = True,
            cfg = "target",
            doc = "The arcc binary the check runs.",
        ),
    },
    toolchains = GO_TOOLCHAINS,
    doc = "Runs `arcc check` on a go_component, expects exit code, and greps stdout/stderr for specific strings.",
)

def _launcher_content_with_golden(argv, golden_file_path):
    command = " ".join([_shell_quote(arg) for arg in argv])
    return "\n".join([
        "#!/bin/sh",
        "set -u",
        'cd "${TEST_SRCDIR:?TEST_SRCDIR is not set}" || exit 2',
        "",
        'output_file=$(mktemp)',
        "status=0",
        command + ' > "$output_file" 2>&1 || status=$?',
        "",
        'if [ "$status" -ne 0 ]; then',
        '  echo "arcc_check_report_golden_test: check failed with exit $status" >&2',
        '  cat "$output_file" >&2',
        '  rm -f "$output_file"',
        '  exit 1',
        'fi',
        "",
        'if ! diff -u %s "$output_file"; then' % _shell_quote(golden_file_path),
        '  echo "arcc_check_report_golden_test: output differs from golden %s" >&2' % _shell_quote(golden_file_path),
        '  rm -f "$output_file"',
        '  exit 1',
        'fi',
        "",
        'rm -f "$output_file"',
        "exit 0",
        "",
    ])

def _arcc_check_report_golden_impl(ctx):
    info = ctx.attr.component[ArccComponentInfo]

    argv = [
        runfiles_path(ctx, ctx.executable._arcc),
        "check",
        runfiles_path(ctx, info.manifest),
    ]
    if info.layout != None:
        argv.append("--package-layout=" + runfiles_path(ctx, info.layout))
    if ctx.attr.format_json:
        argv.append("--format=json")

    golden_path = runfiles_path(ctx, ctx.file.golden)

    launcher = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(
        output = launcher,
        content = _launcher_content_with_golden(argv, golden_path),
        is_executable = True,
    )

    runfiles = ctx.runfiles(files = [ctx.file.golden], transitive_files = go_sdk_srcs(ctx))
    runfiles = runfiles.merge(ctx.attr.component[DefaultInfo].default_runfiles)
    runfiles = runfiles.merge(ctx.attr._arcc[DefaultInfo].default_runfiles)

    return [DefaultInfo(executable = launcher, runfiles = runfiles)]

arcc_check_report_golden_test = rule(
    implementation = _arcc_check_report_golden_impl,
    test = True,
    attrs = {
        "component": attr.label(
            mandatory = True,
            providers = [ArccComponentInfo],
            doc = "The go_component target to check.",
        ),
        "golden": attr.label(
            mandatory = True,
            allow_single_file = True,
            doc = "Golden report file to compare against.",
        ),
        "format_json": attr.bool(
            default = False,
            doc = "Whether to pass --format=json to arcc check.",
        ),
        "_arcc": attr.label(
            default = ARCC_TARGET,
            executable = True,
            cfg = "target",
            doc = "The arcc binary the check runs.",
        ),
    },
    toolchains = GO_TOOLCHAINS,
    doc = "Runs `arcc check` on a go_component hermetically and compares its report output against a golden file.",
)
