"""The `.check` assertion rules: assert a checked component's canonical report
artifact — the record its ordinary analysis action already produced (design
R8, §Build topology, Step 5 task 06).

The rules never re-run `arcc check`: the component's ArccCheck action is the
one analysis command, and these launchers consume its persisted
`ArccComponentInfo.report` through `command.bzl`'s report-assertion argv.
`arcc_check_test` asserts the recorded verdict with `arcc verdict`; the grep
rule asserts the same verdict and then fixed-string-greps the report; the
golden rule diffs the report against a golden byte-for-byte. Launchers `cd`
to the runfiles root — the frame every staged path is expressed in — and
stage nothing but the report plus the assertion-specific arcc or golden
inputs: no SDK sources, no manifest/layout, no component source closure, so
an assertion cannot become a second, drifting analysis path.

`arcc_checked_analysis_test` remains the execution half of the checked-
component action (Step 5 task 04): it re-runs the exact command the
component's ArccCheck action runs and requires byte-identical artifacts and
the expected verdict. Both rule families build their commands through
`command.bzl` — the analysis argv and the report-assertion argv — so the
assertion and the action cannot drift (R7).
"""

load("//bazel_rules:providers.bzl", "ArccComponentInfo")
load("//bazel_rules/go:providers.bzl", "ArccStdlibMapInfo")
load(":command.bzl", "arcc_check_argv", "arcc_verdict_argv")
load(":go_adapter.bzl", "ARCC_TARGET", "GO_TOOLCHAINS", "go_sdk_srcs")
load(":paths.bzl", "runfiles_path")
load(":stdlib_map.bzl", "stdlib_map_default_attr")

def _shell_quote(arg):
    # Runfiles-root-relative paths hold no shell metacharacters, but quoting is
    # free insurance and keeps the generated script obviously safe to read.
    return "'" + arg.replace("'", "'\\''") + "'"

def _launcher_content(argv):
    """Launcher for `arcc_check_test`: assert the report's recorded verdict.

    `arcc verdict`'s own exit-code mapping is the test result — 0 matches the
    expectation, 1 is a verdict mismatch whose diagnostic names both the
    expected and the actual verdict, and 2 is an open/decode/usage error.
    `argv` is `command.bzl`'s report-assertion argv with runfiles-frame paths.
    """
    command = " ".join([_shell_quote(arg) for arg in argv])

    return "\n".join([
        "#!/bin/sh",
        "# Generated by arcc_check_test — do not edit.",
        "#",
        "# Bazel starts a test with the runfiles root at $TEST_SRCDIR. The",
        "# component's canonical report — the artifact its analysis action",
        "# produced — is staged there, and `arcc verdict` asserts its recorded",
        "# verdict. The analysis itself is never rerun (design R8).",
        "set -u",
        'cd "${TEST_SRCDIR:?TEST_SRCDIR is not set}" || exit 2',
        "",
        command,
        "",
        'exit "$?"',
        "",
    ])

def _checked_launcher_arg(arg):
    """Quote one launcher argv element.

    Artifact destination arguments name `$TEST_TMPDIR`, which only the shell
    may expand, so they are double-quoted; every other element is a
    runfiles-frame path with no metacharacters and gets the ordinary single
    quoting.
    """
    if "$TEST_TMPDIR" in arg:
        return '"' + arg + '"'
    return _shell_quote(arg)

_CHECKED_VERDICTS = ("pass", "fail")

def _require_checked_component(info, rule_name, label):
    """Fails analysis when the component is an asserted one (task req 7, AC 5).

    An asserted component has no checked report: running the assertion rules
    against it would execute a full check the asserted path deliberately
    avoided and let an asserted surface masquerade as a passing check —
    exactly what design I6/R8 forbid. The macro simply omits the `.check`
    for asserted components; this guard catches an explicit, hand-written
    target and fails with a diagnostic naming both targets.
    """
    if info.report == None:
        fail(("%s %s: component %s is an asserted component (provenance %r); it has no checked " +
              "report, so there is no checked verdict to assert. An asserted surface must never " +
              "be treated as a passing check (design I6, R8).") % (
            rule_name,
            label,
            info.component_name,
            info.provenance,
        ))

def _validated_verdict(attr_value, label):
    """The expected report verdict, validated at analysis time.

    The value is interpolated into generated shell code, so it must be one of
    the two documented enum constants — anything else is a BUILD-authoring
    error rejected here, never an unescaped string in the launcher.
    """
    if attr_value not in _CHECKED_VERDICTS:
        fail("arcc_checked_analysis_test %s: expect_verdict must be one of %s, got %r" % (
            label,
            ", ".join(_CHECKED_VERDICTS),
            attr_value,
        ))
    return attr_value

def _checked_analysis_launcher(argv, expected_report, expected_surface, expect_verdict, map_path, arcc):
    """Launcher for `arcc_checked_analysis_test`.

    Runs the component's exact analysis command twice into the test scratch
    directory, compares both runs' artifacts byte-for-byte with each other and
    with the analysis action's own outputs, and asserts the report verdict.
    `argv` is the factored command with runfiles-frame paths; the two artifact
    destinations are `$TEST_TMPDIR`-relative and double-quoted so the shell
    expands them.
    """
    command = " ".join([_checked_launcher_arg(arg) for arg in argv])
    run1 = command.replace("runX", "run1")
    run2 = run1.replace("run1.report.json", "run2.report.json").replace("run1.surface.json", "run2.surface.json")
    return "\n".join([
        "#!/bin/sh",
        "# Generated by arcc_checked_analysis_test — do not edit.",
        "#",
        "# Execution coverage for the checked-component analysis action: the",
        "# same command the action runs (command.bzl), executed twice in the",
        "# test sandbox, must reproduce the action's report and surface",
        "# byte-identically (determinism), and the report must carry the",
        "# expected verdict — pass for a conforming component, fail for a",
        "# violating one (violations are data, never action failures).",
        "set -eu",
        'cd "${TEST_SRCDIR:?TEST_SRCDIR is not set}" || exit 2',
        "",
        run1,
        run2,
        "",
        'if ! cmp -s "$TEST_TMPDIR/run1.report.json" "$TEST_TMPDIR/run2.report.json"; then',
        '  echo "arcc_checked_analysis_test: report differs between identical runs" >&2',
        "  exit 1",
        "fi",
        'if ! cmp -s "$TEST_TMPDIR/run1.surface.json" "$TEST_TMPDIR/run2.surface.json"; then',
        '  echo "arcc_checked_analysis_test: surface differs between identical runs" >&2',
        "  exit 1",
        "fi",
        'if ! cmp -s ' + _shell_quote(expected_report) + ' "$TEST_TMPDIR/run1.report.json"; then',
        '  echo "arcc_checked_analysis_test: reproduced report differs from the analysis action\'s report" >&2',
        "  diff -u " + _shell_quote(expected_report) + ' "$TEST_TMPDIR/run1.report.json" >&2 || true',
        "  exit 1",
        "fi",
        'if ! cmp -s ' + _shell_quote(expected_surface) + ' "$TEST_TMPDIR/run1.surface.json"; then',
        '  echo "arcc_checked_analysis_test: reproduced surface differs from the analysis action\'s surface" >&2',
        "  diff -u " + _shell_quote(expected_surface) + ' "$TEST_TMPDIR/run1.surface.json" >&2 || true',
        "  exit 1",
        "fi",
        "",
        'if ! grep -q \'"verdict": "' + expect_verdict + '"\' "$TEST_TMPDIR/run1.report.json"; then',
        '  echo "arcc_checked_analysis_test: expected verdict ' + expect_verdict + ' in report:" >&2',
        '  cat "$TEST_TMPDIR/run1.report.json" >&2',
        "  exit 1",
        "fi",
        "",
        "# Target identity (AC 6): the surface's SDK key must identify the",
        "# attached stdlib map exactly. The action itself already validated",
        "# the full key (including classifier hash and tags) against the",
        "# layout's pinned platform; this re-checks the identity fields the",
        "# surface carries against the map artifact.",
        'toolchain=$(sed -n \'s/.*"toolchainVersion": "\\([^"]*\\)".*/\\1/p\' "$TEST_TMPDIR/run1.surface.json")',
        'goos=$(sed -n \'s/.*"goos": "\\([^"]*\\)".*/\\1/p\' "$TEST_TMPDIR/run1.surface.json")',
        'goarch=$(sed -n \'s/.*"goarch": "\\([^"]*\\)".*/\\1/p\' "$TEST_TMPDIR/run1.surface.json")',
        'if [ -z "$toolchain" ] || [ -z "$goos" ] || [ -z "$goarch" ]; then',
        '  echo "arcc_checked_analysis_test: surface carries no SDK key identity fields" >&2',
        '  cat "$TEST_TMPDIR/run1.surface.json" >&2',
        "  exit 1",
        "fi",
        'if ! ' + _shell_quote(arcc) + ' stdlibmap inspect ' + _shell_quote(map_path) +
        ' --expect-key="toolchain_version=$toolchain,goos=$goos,goarch=$goarch" >/dev/null 2>&1; then',
        '  echo "arcc_checked_analysis_test: surface SDK key does not identify the attached stdlib map" >&2',
        "  exit 1",
        "fi",
        "",
        "exit 0",
        "",
    ])

def _arcc_checked_analysis_impl(ctx):
    info = ctx.attr.component[ArccComponentInfo]
    _require_checked_component(info, "arcc_checked_analysis_test", ctx.label)
    expect_verdict = _validated_verdict(ctx.attr.expect_verdict, ctx.label)

    map_info = ctx.attr._stdlib_map
    if type(map_info) == type([]):
        map_info = map_info[0]
    map_file = map_info[ArccStdlibMapInfo].map
    argv = arcc_check_argv(
        arcc = runfiles_path(ctx, ctx.executable._arcc),
        manifest = runfiles_path(ctx, info.manifest),
        layout = runfiles_path(ctx, info.layout),
        stdlib_map = runfiles_path(ctx, map_file),
        report_out = "$TEST_TMPDIR/runX.report.json",
        surface_out = "$TEST_TMPDIR/runX.surface.json",
        verdict_only = True,
    )

    launcher = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(
        output = launcher,
        content = _checked_analysis_launcher(
            argv,
            runfiles_path(ctx, info.report),
            runfiles_path(ctx, info.surface),
            ctx.attr.expect_verdict,
            runfiles_path(ctx, map_file),
            runfiles_path(ctx, ctx.executable._arcc),
        ),
        is_executable = True,
    )

    # The stdlib source the layout names lives in the Go SDK; arcc type-checks
    # the closure from it, so it must be present in the sandbox. The provider's
    # report and surface — the exact artifacts the re-executed command must
    # reproduce — bring the analysis action's own outputs, and through its
    # declared inputs the dependency producer chain, into the test's build
    # graph.
    runfiles = ctx.runfiles(transitive_files = go_sdk_srcs(ctx))
    runfiles = runfiles.merge(ctx.attr.component[DefaultInfo].default_runfiles)
    runfiles = runfiles.merge(ctx.attr._arcc[DefaultInfo].default_runfiles)
    runfiles = runfiles.merge(ctx.runfiles(files = [map_file, info.report, info.surface]))

    return [DefaultInfo(executable = launcher, runfiles = runfiles)]

arcc_checked_analysis_test = rule(
    implementation = _arcc_checked_analysis_impl,
    test = True,
    attrs = {
        "component": attr.label(
            mandatory = True,
            providers = [ArccComponentInfo],
            doc = "The checked go_component target whose analysis to re-execute.",
        ),
        "expect_verdict": attr.string(
            default = "pass",
            doc = "The report verdict the analysis must produce: \"pass\" for a " +
                  "conforming component, \"fail\" for a violating one.",
        ),
        "_arcc": attr.label(
            default = ARCC_TARGET,
            executable = True,
            cfg = "target",
            doc = "The arcc binary the check runs.",
        ),
        "_stdlib_map": stdlib_map_default_attr(),
    },
    toolchains = GO_TOOLCHAINS,
    doc = "Re-executes a checked component's analysis command and requires " +
          "byte-identical report/surface artifacts and the expected verdict.",
)

def _arcc_check_impl(ctx):
    info = ctx.attr.component[ArccComponentInfo]
    _require_checked_component(info, "arcc_check_test", ctx.label)

    expect = "fail" if ctx.attr.expect_violation else "pass"
    argv = arcc_verdict_argv(
        arcc = runfiles_path(ctx, ctx.executable._arcc),
        report = runfiles_path(ctx, info.report),
        expect = expect,
    )

    launcher = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(
        output = launcher,
        content = _launcher_content(argv),
        is_executable = True,
    )

    # The provider's canonical report is the only staged artifact: declaring
    # it as a runfile builds the component's analysis action (and, through
    # the action's declared inputs, the dependency producer chain) exactly
    # once (design §Build topology). No SDK sources, no manifest/layout, no
    # component source closure — the assertion never re-runs the analysis.
    runfiles = ctx.runfiles(files = [info.report])
    runfiles = runfiles.merge(ctx.attr._arcc[DefaultInfo].default_runfiles)

    return [DefaultInfo(executable = launcher, runfiles = runfiles)]

arcc_check_test = rule(
    implementation = _arcc_check_impl,
    test = True,
    attrs = {
        "component": attr.label(
            mandatory = True,
            providers = [ArccComponentInfo],
            doc = "The checked go_component target whose canonical report verdict is asserted.",
        ),
        "expect_violation": attr.bool(
            default = False,
            doc = "Test-only. When true the test passes iff the report's recorded " +
                  "verdict is `fail` — used to exercise the negative path " +
                  "(`arcc verdict --expect=fail`). Real `.check` targets, which " +
                  "the go_component macro generates, leave this False.",
        ),
        "_arcc": attr.label(
            default = ARCC_TARGET,
            executable = True,
            cfg = "target",
            doc = "The arcc binary whose `verdict` command asserts the report.",
        ),
    },
    doc = "Asserts a checked go_component's canonical report verdict with " +
          "`arcc verdict <report> --expect=pass|fail`, without re-running the analysis.",
)

def _launcher_content_with_grep(verdict_argv, report_path, expected_strings, expect_verdict):
    """Launcher for `arcc_check_grep_test`: verdict, then fixed strings in the report.

    The report-assertion argv (command.bzl) runs first — the report must carry
    the expected verdict — then each expected string is fixed-string-grepped
    against the canonical report artifact. A missing string names itself and
    dumps the report, keeping the diagnostic actionable (task req 2).
    """
    command = " ".join([_shell_quote(arg) for arg in verdict_argv])

    lines = [
        "#!/bin/sh",
        "# Generated by arcc_check_grep_test — do not edit.",
        "#",
        "# The component's canonical report — the artifact its analysis action",
        "# produced — is staged in the runfiles. The recorded verdict is",
        "# asserted with `arcc verdict` and the expected strings are grepped",
        "# from the same artifact; the analysis is never rerun (design R8).",
        "set -u",
        'cd "${TEST_SRCDIR:?TEST_SRCDIR is not set}" || exit 2',
        "",
        command,
        "status=$?",
        "",
        'if [ "$status" -ne 0 ]; then',
        '  echo "arcc_check_grep_test: the report\'s verdict does not match --expect=%s (arcc verdict exit $status)" >&2' % expect_verdict,
        "  cat " + _shell_quote(report_path) + " >&2",
        "  exit 1",
        "fi",
        "",
    ]

    for s in expected_strings:
        # `--` keeps a pattern beginning with `-` from being parsed as an
        # option; the diagnostic passes the string as printf data (single
        # shell-quoted argument), so quotes, `$(...)`, `%` signs and newlines
        # in an expected string stay data — never generated shell code.
        lines += [
            'if ! grep -F -- %s %s > /dev/null; then' % (_shell_quote(s), _shell_quote(report_path)),
            '  echo "arcc_check_grep_test: expected string not found in the component report:" >&2',
            "  printf '%s\\n' " + _shell_quote(s) + " >&2",
            "  cat " + _shell_quote(report_path) + " >&2",
            "  exit 1",
            "fi",
        ]

    return "\n".join(lines + ["", "exit 0", ""])

_EXPECT_STATUSES = (0, 1)

def _arcc_check_grep_impl(ctx):
    info = ctx.attr.component[ArccComponentInfo]
    _require_checked_component(info, "arcc_check_grep_test", ctx.label)

    # expect_status 0 conforms (pass), 1 is the violation verdict (fail) — the
    # same vocabulary the verdict command consumes. Anything else is a
    # BUILD-authoring error rejected at analysis time.
    if ctx.attr.expect_status not in _EXPECT_STATUSES:
        fail("arcc_check_grep_test %s: expect_status must be one of %s, got %d" % (
            ctx.label,
            ", ".join([str(s) for s in _EXPECT_STATUSES]),
            ctx.attr.expect_status,
        ))
    expect = "pass" if ctx.attr.expect_status == 0 else "fail"
    report_path = runfiles_path(ctx, info.report)

    verdict_argv = arcc_verdict_argv(
        arcc = runfiles_path(ctx, ctx.executable._arcc),
        report = report_path,
        expect = expect,
    )

    launcher = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(
        output = launcher,
        content = _launcher_content_with_grep(verdict_argv, report_path, ctx.attr.expected_strings, expect),
        is_executable = True,
    )

    # The canonical report is the only staged artifact: staging it builds the
    # component's analysis action (and its dependency producer chain) exactly
    # once. The grep reads the producer's report — no duplicate CLI run
    # exists to drift from it.
    runfiles = ctx.runfiles(files = [info.report])
    runfiles = runfiles.merge(ctx.attr._arcc[DefaultInfo].default_runfiles)

    return [DefaultInfo(executable = launcher, runfiles = runfiles)]

arcc_check_grep_test = rule(
    implementation = _arcc_check_grep_impl,
    test = True,
    attrs = {
        "component": attr.label(
            mandatory = True,
            providers = [ArccComponentInfo],
            doc = "The checked go_component target whose canonical report is searched.",
        ),
        "expected_strings": attr.string_list(
            mandatory = True,
            doc = "List of strings to grep in the component's canonical report.",
        ),
        "expect_status": attr.int(
            default = 1,
            doc = "Expected report outcome: 0 conforms (verdict pass), 1 is the " +
                  "violation verdict (fail). The rule asserts the recorded " +
                  "verdict before grepping.",
        ),
        "_arcc": attr.label(
            default = ARCC_TARGET,
            executable = True,
            cfg = "target",
            doc = "The arcc binary whose `verdict` command asserts the report.",
        ),
    },
    doc = "Asserts a checked go_component's report verdict and greps its " +
          "canonical report artifact for specific strings, without re-running the analysis.",
)

def _launcher_content_with_golden(report_path, golden_file_path):
    """Launcher for `arcc_check_report_golden_test`: diff the canonical report.

    The golden comparison is byte-for-byte against the provider's canonical
    report artifact — the exact bytes the analysis action wrote. The report
    carries its verdict, so a golden diff pins the full persisted artifact;
    the analysis is never rerun (task req 3).
    """
    return "\n".join([
        "#!/bin/sh",
        "# Generated by arcc_check_report_golden_test — do not edit.",
        "#",
        "# The component's canonical report — the artifact its analysis action",
        "# produced — is diffed byte-for-byte against the golden. The analysis",
        "# is never rerun (design R8).",
        "set -u",
        'cd "${TEST_SRCDIR:?TEST_SRCDIR is not set}" || exit 2',
        "",
        'if ! diff -u %s %s; then' % (_shell_quote(golden_file_path), _shell_quote(report_path)),
        '  echo "arcc_check_report_golden_test: the canonical report differs from golden %s" >&2' % _shell_quote(golden_file_path),
        "  exit 1",
        "fi",
        "",
        "exit 0",
        "",
    ])

def _arcc_check_report_golden_impl(ctx):
    info = ctx.attr.component[ArccComponentInfo]
    _require_checked_component(info, "arcc_check_report_golden_test", ctx.label)

    report_path = runfiles_path(ctx, info.report)
    golden_path = runfiles_path(ctx, ctx.file.golden)

    launcher = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(
        output = launcher,
        content = _launcher_content_with_golden(report_path, golden_path),
        is_executable = True,
    )

    # The canonical report and the golden are the only staged artifacts;
    # staging the report builds the component's analysis action (and its
    # dependency producer chain) exactly once. No arcc: the golden diff needs
    # no tool.
    runfiles = ctx.runfiles(files = [info.report, ctx.file.golden])

    return [DefaultInfo(executable = launcher, runfiles = runfiles)]

arcc_check_report_golden_test = rule(
    implementation = _arcc_check_report_golden_impl,
    test = True,
    attrs = {
        "component": attr.label(
            mandatory = True,
            providers = [ArccComponentInfo],
            doc = "The checked go_component target whose canonical report is compared.",
        ),
        "golden": attr.label(
            mandatory = True,
            allow_single_file = True,
            doc = "Golden canonical report artifact to compare against byte-for-byte.",
        ),
    },
    doc = "Compares a checked go_component's canonical report artifact against a " +
          "golden file byte-for-byte, without re-running the analysis.",
)
