load("@rules_go//go:def.bzl", "go_library")
load("//bazel_rules/go/tests:testing.bzl", "testing_go_component")

go_library(
    name = "unused_consumer",
    srcs = ["unused_consumer.go"],
    importpath = "example.com/infra/unused_consumer",
    visibility = ["//visibility:public"],
)

testing_go_component(
    name = "unused_consumer_component",
    infra_deps = ["//bazel_rules/go/tests/testdata/infra/runtime:runtime_component"],
    interface = ":unused_consumer",
    test_infra_attach = "ALWAYS",
    test_infra_patterns = ["example.com/infra/runtime*"],
    visibility = ["//visibility:public"],
)
