package manifestparity

import (
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"
	"testing"

	"github.com/ono-sendai-labs/architectural-contracts/go/internal/hostpolicy"
	"github.com/ono-sendai-labs/architectural-contracts/go/internal/manifest"
)

// Run checks that the manifests generated by the go_component Bazel rule agree
// semantically with their hand-written colocated component.textproto counterparts.
//
// It is driven by Bazel, which passes every relevant manifest as a positional
// argument. Under plain `go test` (no arguments passed), it skips.
func Run(t testing.TB, files []string) {
	if len(files) == 0 {
		t.Skip("no manifests passed; this parity test is driven by Bazel (see BUILD.bazel)")
	}

	// Bazel expands $(rootpath ...) relative to the runfiles root, which is
	// $TEST_SRCDIR/$TEST_WORKSPACE, not the test's working directory.
	runfilesRoot := filepath.Join(os.Getenv("TEST_SRCDIR"), os.Getenv("TEST_WORKSPACE"))

	// Both a component's generated manifest and its checked-in manifest sit in
	// the same source directory, so the directory name keys them together.
	generated := map[string]string{}
	checkedIn := map[string]string{}
	for _, f := range files {
		base := filepath.Base(f)
		dir := filepath.Base(filepath.Dir(f))
		var resolved string
		if filepath.IsAbs(f) || runfilesRoot == "" {
			resolved = f
		} else {
			resolved = filepath.Join(runfilesRoot, f)
		}
		switch {
		case strings.HasSuffix(base, ".package-layout.json"):
			// The layout travels with the manifest but is not compared here.
			continue
		case base == "component.textproto":
			checkedIn[dir] = resolved
		case strings.HasSuffix(base, "_component.component.textproto"):
			generated[dir] = resolved
		default:
			t.Errorf("unexpected manifest argument %q", f)
		}
	}

	allDirs := map[string]bool{}
	for dir := range generated {
		allDirs[dir] = true
	}
	for dir := range checkedIn {
		allDirs[dir] = true
	}

	if len(allDirs) == 0 {
		t.Fatal("no manifests found among the arguments")
	}

	dirs := make([]string, 0, len(allDirs))
	for dir := range allDirs {
		dirs = append(dirs, dir)
	}
	sort.Strings(dirs)

	for _, dir := range dirs {
		genPath, hasGen := generated[dir]
		chkPath, hasChk := checkedIn[dir]
		if !hasGen {
			t.Errorf("%s: checked-in manifest has no generated counterpart", dir)
			continue
		}
		if !hasChk {
			t.Errorf("%s: generated manifest has no checked-in counterpart", dir)
			continue
		}
		gen := parse(t, genPath)
		chk := parse(t, chkPath)
		CompareManifests(t, dir, gen, chk)
	}
}

func parse(t testing.TB, path string) manifest.Manifest {
	t.Helper()
	f, err := os.Open(path)
	if err != nil {
		t.Fatalf("opening %s: %v", path, err)
	}
	defer f.Close()
	m, err := manifest.Parse(f)
	if err != nil {
		t.Fatalf("parsing %s: %v", path, err)
	}
	return m
}

// CompareManifests compares a generated manifest against a checked-in manifest
// for semantic equivalence, ignoring incidental differences (e.g., target name suffix,
// path frames for interface files).
func CompareManifests(t testing.TB, dir string, gen, chk manifest.Manifest) {
	t.Helper()

	// Name: the generated name is the Bazel target, which suffixes `_component`.
	if got := strings.TrimSuffix(gen.Name, "_component"); got != chk.Name {
		t.Errorf("%s: name = %q (normalized %q), want %q", dir, gen.Name, got, chk.Name)
	}

	// Interface files: every file the checked-in manifest calls interface must
	// appear in the generated interface set (compared by basename).
	genIface := basenames(gen.InterfaceFiles)
	for _, want := range basenames(chk.InterfaceFiles) {
		if !slices.Contains(genIface, want) {
			t.Errorf("%s: checked-in interface file %q missing from generated interface files %v", dir, want, genIface)
		}
	}

	// Members: check equivalence considering implicit interface package membership.
	compareMembers(t, dir, gen, chk)

	// Interface style: same style.
	if gen.InterfaceStyle != chk.InterfaceStyle {
		t.Errorf("%s: interface style = %v, want %v", dir, gen.InterfaceStyle, chk.InterfaceStyle)
	}

	// Certification is an emitter self-declaration and is part of parity: a
	// checked-in mirror must not silently claim a different check participation
	// state than the generated manifest.
	if gen.OwnCheckRuns != chk.OwnCheckRuns {
		t.Errorf("%s: own_check_runs = %t, want %t", dir, gen.OwnCheckRuns, chk.OwnCheckRuns)
	}

	// Declared authority: same set.
	if got, want := sorted(gen.DeclaredAuthority), sorted(chk.DeclaredAuthority); !slices.Equal(got, want) {
		t.Errorf("%s: declared authority = %v, want %v", dir, got, want)
	}

	// Component dependencies: same set of names, `_component` suffix normalized.
	if got, want := depNames(gen.ComponentDependencies), depNames(chk.ComponentDependencies); !slices.Equal(got, want) {
		t.Errorf("%s: component-dependency names = %v, want %v", dir, got, want)
	}
}

// canonicalize maps an import path through the host's canonicalization policy.
// The generated Bazel manifest and its checked-in mirror may describe the same
// package in different namespaces when a host rewrites import prefixes, so
// every import-path comparison in this helper canonicalizes both sides first.
// Non-import-path fields (names, interface-file basenames, authority values)
// are deliberately left alone.
func canonicalize(paths []string) []string {
	out := make([]string, len(paths))
	for i, p := range paths {
		out[i] = hostpolicy.CanonicalizePath(p)
	}
	return out
}

// compareMembers checks that generated and checked-in member sets match.
//
// Per requirement M5, the interface package is implicitly a member of a component.
// The Bazel rule emitter always includes the interface package in generated.Members.
// Checked-in manifests may either list the interface package explicitly in members
// or omit it relying on implicit membership.
//
// Therefore, the member sets match if:
//  1. sorted(gen.Members) == sorted(chk.Members) (checked-in explicitly lists the interface package), OR
//  2. sorted(gen.Members) == sorted(chk.Members + implicit_interface_package) (checked-in omitted the implicit interface package).
func compareMembers(t testing.TB, dir string, gen, chk manifest.Manifest) {
	t.Helper()
	got := sorted(canonicalize(gen.Members))
	want := sorted(canonicalize(chk.Members))
	if slices.Equal(got, want) {
		return
	}

	extraInGen := diff(got, want)
	missingInGen := diff(want, got)

	if len(missingInGen) == 0 && len(extraInGen) == 1 {
		// If gen has exactly one extra member and it is the component's interface package,
		// allow it per requirement M5 implicit membership rule.
		extraPkg := extraInGen[0]
		if strings.HasSuffix(extraPkg, "/"+chk.Name) || extraPkg == chk.Name {
			return
		}
	}

	t.Errorf("%s: members = %v, want %v", dir, got, want)
}

func diff(a, b []string) []string {
	var res []string
	for _, x := range a {
		if !slices.Contains(b, x) {
			res = append(res, x)
		}
	}
	return res
}

func basenames(paths []string) []string {
	out := make([]string, len(paths))
	for i, p := range paths {
		out[i] = filepath.Base(p)
	}
	sort.Strings(out)
	return out
}

func depNames(deps []manifest.ComponentDependency) []string {
	out := make([]string, len(deps))
	for i, d := range deps {
		out[i] = strings.TrimSuffix(d.Name, "_component")
	}
	sort.Strings(out)
	return out
}

func sorted(s []string) []string {
	out := append([]string(nil), s...)
	sort.Strings(out)
	return out
}
