"""Shared pattern test cases between Go and Starlark."""

PATTERN_CASES = [
    struct(pattern = "example.com/foo", path = "example.com/foo", want = True, malformed = False),
    struct(pattern = "example.com/foo", path = "example.com/bar", want = False, malformed = False),
    struct(pattern = "example.com/foo/*", path = "example.com/foo/bar", want = True, malformed = False),
    struct(pattern = "example.com/foo/*", path = "example.com/foo/bar/baz", want = False, malformed = False),
    struct(pattern = "example.com/foo/*", path = "example.com/foo", want = False, malformed = False),
    struct(pattern = "example.com/foo/b*", path = "example.com/foo/bar", want = True, malformed = False),
    struct(pattern = "example.com/foo/b*", path = "example.com/foo/car", want = False, malformed = False),
    struct(pattern = "example.com/foo/ba?", path = "example.com/foo/bar", want = True, malformed = False),
    struct(pattern = "example.com/foo/ba?", path = "example.com/foo/b", want = False, malformed = False),
    struct(pattern = "example.com/foo/ba?", path = "example.com/foo/barr", want = False, malformed = False),
    struct(pattern = "example.com/foo/ba?", path = "example.com/foo/ba/", want = False, malformed = False),
    struct(pattern = "*.com/*/*", path = "example.com/foo/bar", want = True, malformed = False),
    struct(pattern = "*.com/*/*", path = "example.com/foo/bar/baz", want = False, malformed = False),
    struct(pattern = "", path = "", want = True, malformed = False),
    struct(pattern = "", path = "a", want = False, malformed = False),
    struct(pattern = "a", path = "", want = False, malformed = False),
    struct(pattern = "example.com/foo*", path = "example.com/foobar", want = True, malformed = False),
    struct(pattern = "example.com/foo*", path = "example.com/foo/bar", want = False, malformed = False),
    struct(pattern = "example.com/foo/\\*", path = "example.com/foo/*", want = True, malformed = False),
    struct(pattern = "example.com/foo/\\*", path = "example.com/foo/bar", want = False, malformed = False),
    struct(pattern = "example.com/v[0-9]", path = "example.com/v1", want = True, malformed = False),
    struct(pattern = "example.com/v[0-9]", path = "example.com/va", want = False, malformed = False),
    struct(pattern = "example.com/v[^0-9]", path = "example.com/va", want = True, malformed = False),
    struct(pattern = "example.com/v[^0-9]", path = "example.com/v1", want = False, malformed = False),
    struct(pattern = "example.com/[\\]]", path = "example.com/]", want = True, malformed = False),
    struct(pattern = "example.com/[\\]]", path = "example.com/a", want = False, malformed = False),
    struct(pattern = "example.com/[]", path = "example.com/a", want = False, malformed = True),
    struct(pattern = "example.com/[^]", path = "example.com/a", want = False, malformed = True),
    struct(pattern = "example.com/[", path = "example.com/a", want = False, malformed = True),
    struct(pattern = "example.com/\\", path = "example.com/a", want = False, malformed = True),
]
