#!/bin/sh
# Step 4 task 06 execution test (ACs 1, 3, 4, 6): the Bazel-built stdlib maps
# validate against their own target SDK keys, reject the other keys, carry
# the representative classifications, and reproduce deterministic bytes for
# identical configurations.
#
# Bazel runs this test in a sandbox with no network and no host `go` binary
# on PATH; the maps themselves were generated by actions whose only tool is
# the arcc generator and whose only Go material is the declared SDK sources
# (design I5: the generator loads the SDK through the layout driver, so the
# action contains no `go` binary, no build cache and no network).

set -eu

arcc="$1"
default_map="$2"
replica_map="$3"
darwin_map="$4"
tagged_map="$5"

pass() { echo "PASS: $1"; }
fail() { echo "FAIL: $1" >&2; exit 1; }

expect_inspect_ok() {
  desc="$1"; shift
  if ! "$arcc" stdlibmap inspect "$@" >/dev/null 2>"$tmp_err"; then
    echo "stderr was:" >&2
    cat "$tmp_err" >&2
    fail "$desc (inspect exited nonzero)"
  fi
  pass "$desc"
}

expect_inspect_fails() {
  desc="$1"; shift
  if "$arcc" stdlibmap inspect "$@" >/dev/null 2>&1; then
    fail "$desc (inspect exited zero; expected key mismatch)"
  fi
  pass "$desc"
}

tmp_err="$(mktemp)"
trap 'rm -f "$tmp_err"' EXIT

# --- AC 3: each map validates against its own key, and rejects the others ---

# Keys by configuration (from the rule's provider fields):
#   default/replica: linux/amd64, cgo disabled, no tags
#   tagged:          linux/amd64, cgo disabled, tag arcc_probe_tag
#   darwin:          darwin/arm64, cgo disabled
expect_inspect_ok "default map accepts its linux/amd64 key" "$default_map" \
  --expect-key=goos=linux,goarch=amd64,cgo_enabled=false,toolchain_version=go1.26.4 summary
expect_inspect_ok "replica map accepts its linux/amd64 key" "$replica_map" \
  --expect-key=goos=linux,goarch=amd64,cgo_enabled=false,toolchain_version=go1.26.4 summary
expect_inspect_ok "tagged map accepts its tagged key" "$tagged_map" \
  --expect-key=goos=linux,goarch=amd64,cgo_enabled=false,toolchain_version=go1.26.4,tag=arcc_probe_tag summary
expect_inspect_ok "darwin map accepts its darwin/arm64 key" "$darwin_map" \
  --expect-key=goos=darwin,goarch=arm64,cgo_enabled=false summary

expect_inspect_fails "default map rejects the tagged key" "$default_map" \
  --expect-key=goos=linux,goarch=amd64,cgo_enabled=false,toolchain_version=go1.26.4,tag=arcc_probe_tag summary
expect_inspect_fails "default map rejects the darwin key" "$default_map" \
  --expect-key=goos=darwin,goarch=arm64 summary
expect_inspect_fails "darwin map rejects the linux/amd64 key" "$darwin_map" \
  --expect-key=goos=linux,goarch=amd64 summary
expect_inspect_fails "replica map rejects a cgo-enabled key" "$replica_map" \
  --expect-key=cgo_enabled=true summary

# --- AC 3: the distinct configurations produce distinct artifacts ---
# (default and cgo-off are the SAME configuration — the default build is
# cgo-free — so their pair is the AC 6 determinism witness instead.)

digests() {
  for m in "$default_map" "$darwin_map" "$tagged_map"; do
    sha256sum "$m" | cut -d' ' -f1
  done
}
if [ "$(digests | sort -u | wc -l)" -ne 3 ]; then
  echo "digests were:" >&2
  digests >&2
  fail "three distinct target configurations produced fewer than 3 distinct digests"
fi
pass "three distinct target configurations produced three distinct maps"

# --- AC 6: identical configurations are deterministic ---
#
# This is a GENUINE two-execution comparison, not action-cache reuse: the
# two targets declare DIFFERENT output paths (arcc_stdlib_map.stdlib-map.json
# vs arcc_stdlib_map_replica.stdlib-map.json), and Bazel's action cache keys
# an entry by the action's output paths as well as its inputs, so the replica
# action's key can never match the default target's cached entry. Both
# actions therefore actually executed — on this one execution host — and
# byte-identical canonical bytes are the determinism guarantee the design
# requires (DR-15), not an artifact of cache sharing.
if ! cmp -s "$default_map" "$replica_map"; then
  fail "two identical configurations (default, replica) produced different canonical bytes"
fi
pass "identical configurations produce byte-identical canonical maps"

if [ "$(sha256sum "$default_map" | cut -d' ' -f1)" != "$(sha256sum "$replica_map" | cut -d' ' -f1)" ]; then
  fail "two identical configurations (default, replica) produced different digests"
fi
pass "identical configurations produce identical digests"

# --- AC 4: representative classifications match the design ---

expect_class() {
  desc="$1"; map="$2"; shift 2
  want="$1"; id="$2"
  got="$("$arcc" stdlibmap inspect "$map" "symbol" "$id" 2>"$tmp_err" | head -1)"
  if [ "$got" != "$id: $want" ]; then
    echo "got: '$got' (want '$id: $want')" >&2
    cat "$tmp_err" >&2
    fail "$desc"
  fi
  pass "$desc"
}

expect_class "os.ReadFile is FILES" "$default_map" "CAPABILITIES [FILES]" os.ReadFile
expect_class "strings.TrimSpace is SAFE" "$default_map" "SAFE" strings.TrimSpace
expect_class "sort.Slice is UNANALYZED" "$default_map" "UNANALYZED" sort.Slice
expect_class "os.Stdin is not pure" "$default_map" "CAPABILITIES [FILES,MODIFY_SYSTEM_STATE,OPERATING_SYSTEM]" os.Stdin
expect_class "io.EOF is SAFE" "$default_map" "SAFE" io.EOF
expect_class "net/http.DefaultClient is NETWORK" "$default_map" "CAPABILITIES [NETWORK]" net/http.DefaultClient
expect_class "unsafe.Pointer is UNANALYZED" "$default_map" "UNANALYZED" unsafe.Pointer

# Init inventory: an init-bearing stdlib package carries an init entry with a
# terminal classification, rendered through the task 01 reader.
if ! "$arcc" stdlibmap inspect "$default_map" init net/http >/dev/null 2>"$tmp_err"; then
  cat "$tmp_err" >&2
  fail "net/http carries an init record"
fi
pass "net/http carries an init record"

# The cross-compiled map is a different artifact: its darwin-only symbols
# exist and the linux-only ones do not, so the two maps cannot be confused.
if "$arcc" stdlibmap inspect "$darwin_map" summary 2>"$tmp_err" | grep -q '^packages: 0'; then
  fail "the darwin map is empty"
fi
pass "the darwin map is populated"

echo "stdlib_map_keys_test: all assertions passed"
