"""Deterministic Bazel graphs for the Step 13 producer-chain benchmark.

Each measured component owns one tiny member package and depends on a checked
PACKAGE_SURFACE component whose one fixed member is a wrapper around the
ordinary entry package. The entry package directly imports every top-level node
and owns the optional type/signature surface, matching Task 1's graph edges.
The layered nodes are covered by a package-level asserted component, so they
remain export-backed ordinary closure without adding a growing typed check to
the measured producer chain. Both checked components therefore parse one fixed
member file while the real aspect and final layouts retain the complete entry
and node closure; each checked component still produces a real surface/report
edge.

Source files are generated from these fixed parameters instead of being copied
from a host tree. The generated bytes are deterministic; only the variant's
fixed-width import-path token changes between otherwise identical members.
"""

load("@rules_arcc//bazel_rules/go:defs.bzl", "PACKAGE_SURFACE", "go_component")
load("@rules_go//go:def.bzl", "go_library")

_BASE_IMPORT = "example.com/arcc-producer-chain"
_VISIBILITY = ["//bazel_rules:__subpackages__"]
_PRIMARY_VARIANTS = [
    (1, 1, 0),
    (1, 2, 0),
    (1, 4, 0),
    (4, 1, 0),
    (4, 2, 0),
    (4, 4, 0),
    (16, 1, 0),
    (16, 2, 0),
    (16, 4, 0),
]
_TYPE_SURFACE_VARIANTS = [
    (1, 1, 0),
    (1, 1, 8),
    (1, 1, 32),
    (1, 1, 128),
]

def _variant_name(depth, width, type_surface, direct_surface = False):
    if direct_surface:
        return "s" + _padded(type_surface, 4)
    return "d" + _padded(depth, 2) + "w" + _padded(width, 2)

def _padded(value, width):
    text = str(value)
    return "0" * (width - len(text)) + text

def _write_source(name, filename, content):
    native.genrule(
        name = name + "_source",
        outs = [filename],
        cmd = "cat > \"$@\" <<'EOF'\n%s\nEOF\n" % content,
        visibility = _VISIBILITY,
    )
    return ":" + name + "_source"

def _library(name, importpath, filename, content, deps = []):
    source = _write_source(name, filename, content)
    go_library(
        name = name,
        srcs = [source],
        deps = deps,
        importpath = importpath,
        visibility = _VISIBILITY,
    )

def _node_importpath(variant, level, index):
    return "%s/%s/node/l%s/i%s" % (_BASE_IMPORT, variant, _padded(level, 2), _padded(index, 2))

def _node_target(variant, level, index):
    return ":%s_node_l%s_i%s" % (variant, _padded(level, 2), _padded(index, 2))

def _entry_source(variant, width, type_surface):
    lines = ["package entry", ""]
    lines.append("import (")
    # Match Task 1: the directly imported entry package fans out to every
    # top-level node, while the checked members stay in separate wrappers.
    for index in range(width):
        lines.append("\t_ \"" + _node_importpath(variant, 0, index) + "\"")
    lines.extend([
        ")",
        "",
        "type Value struct { Name string }",
        "",
        "func Make() Value { return Value{Name: \"fixed\"} }",
    ])
    for type_index in range(type_surface):
        suffix = _padded(type_index, 3)
        lines.extend([
            "",
            "type PublicType" + suffix + " struct { Field string }",
            "",
            "func PublicFunc" + suffix + "(value PublicType" + suffix + ") PublicType" + suffix + " { return value }",
        ])
    return "\n".join(lines)

def _node_source(variant, depth, width, level, index):
    # The component layout derives a package name from the final import-path
    # segment. Keep the generated source clause aligned with that deterministic
    # adapter fallback rather than relying on a source read during analysis.
    lines = ["package i" + _padded(index, 2)]
    imports = []
    if level + 1 < depth:
        for child in range(width):
            imports.append(_node_importpath(variant, level + 1, child))
    if imports:
        lines.append("")
        lines.append("import (")
        for importpath in imports:
            lines.append("\t_ \"" + importpath + "\"")
        lines.extend([")", ""])
    return "\n".join(lines)

def _member_source(variant):
    entry = "%s/%s/entry" % (_BASE_IMPORT, variant)
    return "\n".join([
        "package member",
        "",
        "import entry \"" + entry + "\"",
        "",
        "func Use() entry.Value { return entry.Make() }",
    ])

def _dependency_member_source(variant):
    entry = "%s/%s/entry" % (_BASE_IMPORT, variant)
    return "\n".join([
        "package dependency_member",
        "",
        "import entry \"" + entry + "\"",
        "",
        "func Use() entry.Value { return entry.Make() }",
    ])

def _define_variant(depth, width, type_surface, direct_surface = False):
    variant = _variant_name(depth, width, type_surface, direct_surface)
    entry_name = variant + "_entry"
    entry_importpath = "%s/%s/entry" % (_BASE_IMPORT, variant)
    node_targets = []

    # Create every node before the entry and members. Forward labels are valid
    # within a BUILD package, and keeping the loop in level/index order makes
    # the source and target inventory stable for the analysis tests.
    for level in range(depth):
        for index in range(width):
            name = "%s_node_l%s_i%s" % (variant, _padded(level, 2), _padded(index, 2))
            child_targets = []
            if level + 1 < depth:
                for child in range(width):
                    child_targets.append(_node_target(variant, level + 1, child))
            _library(
                name = name,
                importpath = _node_importpath(variant, level, index),
                filename = name + ".go",
                content = _node_source(variant, depth, width, level, index),
                deps = child_targets,
            )
            node_targets.append(":" + name)

    top_node_targets = [
        _node_target(variant, 0, index)
        for index in range(width)
    ]
    _library(
        name = entry_name,
        importpath = entry_importpath,
        filename = entry_name + ".go",
        content = _entry_source(variant, width, type_surface),
        deps = top_node_targets,
    )

    member_name = variant + "_member"
    _library(
        name = member_name,
        importpath = "%s/%s/member" % (_BASE_IMPORT, variant),
        filename = member_name + ".go",
        content = _member_source(variant),
        deps = [":" + entry_name],
    )

    dependency_member_name = variant + "_dependency_member"
    _library(
        name = dependency_member_name,
        importpath = "%s/%s/dependency_member" % (_BASE_IMPORT, variant),
        filename = dependency_member_name + ".go",
        content = _dependency_member_source(variant),
        deps = [":" + entry_name],
    )

    dependency_name = variant + "_dependency_component"
    nodes_component_name = variant + "_nodes_component"
    go_component(
        name = nodes_component_name,
        authority = "UNKNOWN",
        interface_style = PACKAGE_SURFACE,
        members = node_targets,
        tags = ["manual"],
        visibility = _VISIBILITY,
    )

    go_component(
        name = dependency_name,
        component_deps = [":" + nodes_component_name],
        interface_style = PACKAGE_SURFACE,
        members = [":" + dependency_member_name],
        tags = ["manual"],
        visibility = _VISIBILITY,
    )

    go_component(
        name = variant + "_component",
        component_deps = [":" + dependency_name],
        interface_style = PACKAGE_SURFACE,
        members = [":" + member_name],
        tags = ["manual"],
        visibility = _VISIBILITY,
    )

def producer_chain_scaling_fixtures():
    """Declares the nine primary and four direct-type-surface variants."""
    for depth, width, type_surface in _PRIMARY_VARIANTS:
        _define_variant(depth, width, type_surface)
    for depth, width, type_surface in _TYPE_SURFACE_VARIANTS:
        # The (1, 1, 0) direct-surface row uses a distinct target name from
        # d01w01, so every row has an independent producer chain.
        _define_variant(depth, width, type_surface, direct_surface = True)
