"""Deterministic Bazel graphs for the Step 13 producer-chain benchmark.

Each measured component owns one tiny member package and depends on a checked
PACKAGE_SURFACE component whose one fixed member is the ordinary entry package.
The layered nodes are covered by a package-level asserted component, so they
remain export-backed ordinary closure without adding a growing typed check to
the measured producer chain. The member source calls the entry package, so the
real aspect and final layout retain the complete closure while the measured
ArccCheck action parses only that one member file; the entry check still
produces a real surface/report edge.

Source files are generated from these fixed parameters instead of being copied
from a host tree. The generated bytes are deterministic; only the variant's
fixed-width import-path token changes between otherwise identical members.
"""

load("@rules_arcc//bazel_rules/go:defs.bzl", "PACKAGE_SURFACE", "go_component")
load("@rules_go//go:def.bzl", "go_library")

_BASE_IMPORT = "example.com/arcc-producer-chain"
_VISIBILITY = ["//bazel_rules:__subpackages__"]
_PRIMARY_VARIANTS = [
    (1, 1, 0),
    (1, 2, 0),
    (1, 4, 0),
    (4, 1, 0),
    (4, 2, 0),
    (4, 4, 0),
    (16, 1, 0),
    (16, 2, 0),
    (16, 4, 0),
]
_TYPE_SURFACE_VARIANTS = [
    (1, 1, 0),
    (1, 1, 8),
    (1, 1, 32),
    (1, 1, 128),
]

def _variant_name(depth, width, type_surface, direct_surface = False):
    if direct_surface:
        return "s" + _padded(type_surface, 4)
    return "d" + _padded(depth, 2) + "w" + _padded(width, 2)

def _padded(value, width):
    text = str(value)
    return "0" * (width - len(text)) + text

def _write_source(name, filename, content):
    native.genrule(
        name = name + "_source",
        outs = [filename],
        cmd = "cat > \"$@\" <<'EOF'\n%s\nEOF\n" % content,
        visibility = _VISIBILITY,
    )
    return ":" + name + "_source"

def _library(name, importpath, filename, content, deps = []):
    source = _write_source(name, filename, content)
    go_library(
        name = name,
        srcs = [source],
        deps = deps,
        importpath = importpath,
        visibility = _VISIBILITY,
    )

def _node_importpath(variant, level, index):
    return "%s/%s/node/l%s/i%s" % (_BASE_IMPORT, variant, _padded(level, 2), _padded(index, 2))

def _node_target(variant, level, index):
    return ":%s_node_l%s_i%s" % (variant, _padded(level, 2), _padded(index, 2))

def _entry_source(variant):
    lines = ["package entry", ""]
    lines.append("import (")
    # Keep the checked dependency's member source fixed across the depth/width
    # series. The first node fans out to all top-level siblings, so this one
    # stable import still reaches the complete ordinary closure.
    lines.append("\t_ \"" + _node_importpath(variant, 0, 0) + "\"")
    lines.extend([
        ")",
        "",
        "type Value struct { Name string }",
        "",
        "func Make() Value { return Value{Name: \"fixed\"} }",
    ])
    return "\n".join(lines)

def _node_source(variant, depth, width, level, index, type_surface):
    # The component layout derives a package name from the final import-path
    # segment. Keep the generated source clause aligned with that deterministic
    # adapter fallback rather than relying on a source read during analysis.
    lines = ["package i" + _padded(index, 2)]
    imports = []
    if level == 0 and index == 0:
        for sibling in range(1, width):
            imports.append(_node_importpath(variant, 0, sibling))
    if level + 1 < depth:
        for child in range(width):
            imports.append(_node_importpath(variant, level + 1, child))
    if imports:
        lines.append("")
        lines.append("import (")
        for importpath in imports:
            lines.append("\t_ \"" + importpath + "\"")
        lines.extend([")", ""])
    if level == 0 and index == 0:
        for type_index in range(type_surface):
            suffix = _padded(type_index, 3)
            lines.extend([
                "",
                "type PublicType" + suffix + " struct { Field string }",
                "",
                "func PublicFunc" + suffix + "(value PublicType" + suffix + ") PublicType" + suffix + " { return value }",
            ])
    return "\n".join(lines)

def _member_source(variant):
    entry = "%s/%s/entry" % (_BASE_IMPORT, variant)
    return "\n".join([
        "package member",
        "",
        "import entry \"" + entry + "\"",
        "",
        "func Use() entry.Value { return entry.Make() }",
    ])

def _define_variant(depth, width, type_surface, direct_surface = False):
    variant = _variant_name(depth, width, type_surface, direct_surface)
    entry_name = variant + "_entry"
    entry_importpath = "%s/%s/entry" % (_BASE_IMPORT, variant)
    node_targets = []

    # Create every node before the entry and member. Forward labels are valid
    # within a BUILD package, and keeping the loop in level/index order makes
    # the source and target inventory stable for the analysis tests.
    for level in range(depth):
        for index in range(width):
            name = "%s_node_l%s_i%s" % (variant, _padded(level, 2), _padded(index, 2))
            child_targets = []
            if level == 0 and index == 0:
                for sibling in range(1, width):
                    child_targets.append(_node_target(variant, 0, sibling))
            if level + 1 < depth:
                for child in range(width):
                    child_targets.append(_node_target(variant, level + 1, child))
            _library(
                name = name,
                importpath = _node_importpath(variant, level, index),
                filename = name + ".go",
                content = _node_source(variant, depth, width, level, index, type_surface),
                deps = child_targets,
            )
            node_targets.append(":" + name)

    top_node_targets = [
        _node_target(variant, 0, index)
        for index in range(width)
    ]
    _library(
        name = entry_name,
        importpath = entry_importpath,
        filename = entry_name + ".go",
        content = _entry_source(variant),
        deps = top_node_targets,
    )

    member_name = variant + "_member"
    _library(
        name = member_name,
        importpath = "%s/%s/member" % (_BASE_IMPORT, variant),
        filename = member_name + ".go",
        content = _member_source(variant),
        deps = [":" + entry_name],
    )

    dependency_name = variant + "_dependency_component"
    nodes_component_name = variant + "_nodes_component"
    go_component(
        name = nodes_component_name,
        authority = "UNKNOWN",
        interface_style = PACKAGE_SURFACE,
        members = node_targets,
        tags = ["manual"],
        visibility = _VISIBILITY,
    )

    go_component(
        name = dependency_name,
        component_deps = [":" + nodes_component_name],
        interface_style = PACKAGE_SURFACE,
        members = [":" + entry_name],
        tags = ["manual"],
        visibility = _VISIBILITY,
    )

    go_component(
        name = variant + "_component",
        component_deps = [":" + dependency_name],
        interface_style = PACKAGE_SURFACE,
        members = [":" + member_name],
        tags = ["manual"],
        visibility = _VISIBILITY,
    )

def producer_chain_scaling_fixtures():
    """Declares the nine primary and four direct-type-surface variants."""
    for depth, width, type_surface in _PRIMARY_VARIANTS:
        _define_variant(depth, width, type_surface)
    for depth, width, type_surface in _TYPE_SURFACE_VARIANTS:
        # The (1, 1, 0) direct-surface row uses a distinct target name from
        # d01w01, so every row has an independent producer chain.
        _define_variant(depth, width, type_surface, direct_surface = True)
