name: "csvfile"
own_check_runs: true
interface_files: "csvfile.go"
members: "github.com/ono-sendai-labs/architectural-contracts/go/examples/csvtool/csvfile"
component_dependencies {
  name: "parsecsv"
  manifest: "../internal/parsecsv/component.textproto"
}
declared_authority: "FILES"
