load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "capanalyzer",
    srcs = ["capanalyzer.go"],
    importpath = "github.com/ono-sendai-labs/architectural-contracts/go/internal/capanalyzer",
    visibility = ["//go:__subpackages__"],
)

go_test(
    name = "capanalyzer_test",
    srcs = ["capanalyzer_test.go"],
    deps = [":capanalyzer"],
)
