name: "goanalysis"
interface_files: "defeatscan.go"
interface_files: "goanalysis.go"
interface_files: "surface_resolver.go"
interface_files: "surfaceinputs.go"
members: "github.com/ono-sendai-labs/architectural-contracts/go/internal/goanalysis"
members: "github.com/ono-sendai-labs/architectural-contracts/go/internal/packagelayout"
component_dependencies {
  name: "artifactio"
  manifest: "../artifactio/component.textproto"
}
component_dependencies {
  name: "facts"
  manifest: "../facts/component.textproto"
}
component_dependencies {
  name: "manifest"
  manifest: "../manifest/component.textproto"
}
component_dependencies {
  name: "schema"
  manifest: "../schema/component.textproto"
}
component_dependencies {
  name: "stdlibauthority"
  manifest: "../stdlibauthority/component.textproto"
}
component_dependencies {
  name: "surface"
  manifest: "../surface/component.textproto"
}
component_dependencies {
  name: "symbol"
  manifest: "../symbol/component.textproto"
}
component_dependencies {
  name: "x-tools"
  manifest: "../xtools/component.textproto"
}
component_dependencies {
  name: "report"
  manifest: "../report/component.textproto"
}
component_dependencies {
  name: "hostpolicy"
  manifest: "../hostpolicy/component.textproto"
}
declared_authority: "FILES"
declared_authority: "EXEC"
declared_authority: "READ_SYSTEM_STATE"
declared_authority: "OPERATING_SYSTEM"
declared_authority: "REFLECT"
declared_authority: "UNSAFE_POINTER"
declared_authority: "MODIFY_SYSTEM_STATE"
declared_authority: "ARBITRARY_EXECUTION"
