name: "toprow"
interface_files: "toprow.go"
members: "github.com/ono-sendai-labs/architectural-contracts/go/examples/csvtool/toprow"
component_dependencies {
  name: "parsecsv"
  manifest: "../internal/parsecsv/component.textproto"
}
