load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "capslockadapter",
    srcs = ["capslockadapter.go"],
    importpath = "github.com/ono-sendai-labs/architectural-contracts/go/internal/capslockadapter",
    visibility = ["//go:__subpackages__"],
    deps = [
        "//go/internal/capanalyzer",
        "//go/internal/packagelayout",
        "@com_github_google_capslock//analyzer",
        "@com_github_google_capslock//interesting",
        "@org_golang_x_tools//go/packages",
    ],
)
