load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "app",
    srcs = ["app.go"],
    importpath = "github.com/ono-sendai-labs/architectural-contracts/go/examples/csvtool/app",
    visibility = ["//visibility:public"],
    deps = [
        "//go/examples/csvtool/csvfile",
        "//go/examples/csvtool/toprow",
    ],
)
