name: "app"
own_check_runs: true
interface_files: "app.go"
members: "github.com/ono-sendai-labs/architectural-contracts/go/examples/csvtool/app"
component_dependencies {
  name: "csvfile"
  manifest: "../csvfile/component.textproto"
}
component_dependencies {
  name: "toprow"
  manifest: "../toprow/component.textproto"
}
