name: "manifest"
interface_files: "authority.go"
interface_files: "manifest.go"
component_dependencies {
  name: "schema"
  manifest: "../schema/component.textproto"
}
component_dependencies {
  name: "protobuf-runtime"
  manifest: "../protobufruntime/component.textproto"
}
members: "github.com/ono-sendai-labs/architectural-contracts/go/internal/manifest"
declared_authority: "READ_SYSTEM_STATE"
declared_authority: "REFLECT"
declared_authority: "RUNTIME"
declared_authority: "SYSTEM_CALLS"
declared_authority: "UNSAFE_POINTER"
