name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    name: Go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go/go.mod
          cache-dependency-path: go/go.mod

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Install protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "36.1"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install protoc-gen-go
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.11

      - name: Run CI
        run: just ci

  selfcheck:
    name: Self-hosting Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go/go.mod
          cache-dependency-path: go/go.mod

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Run Selfcheck
        run: just selfcheck
